import type { Variants } from "framer-motion";
export const EASE_CURVE = [0.22, 1, 0.36, 1] as const;
export const sectionViewport = { once: true, margin: "-100px" } as const;
export const cardViewport     = { once: true, margin: "-50px"  } as const;
export const fadeInUp: Variants = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.7, ease: EASE_CURVE } } };
export const fadeInLeft: Variants = { hidden: { opacity: 0, x: -32 }, visible: { opacity: 1, x: 0, transition: { duration: 0.8, ease: EASE_CURVE } } };
export const fadeInRight: Variants = { hidden: { opacity: 0, x: 32 }, visible: { opacity: 1, x: 0, transition: { duration: 0.8, ease: EASE_CURVE } } };
export const scaleIn: Variants = { hidden: { opacity: 0, scale: 0.95 }, visible: { opacity: 1, scale: 1, transition: { duration: 0.5, ease: EASE_CURVE } } };
export const staggerContainer: Variants = { hidden: {}, visible: { transition: { staggerChildren: 0.1, delayChildren: 0.1 } } };
export const staggerContainerFast: Variants = { hidden: {}, visible: { transition: { staggerChildren: 0.07, delayChildren: 0.05 } } };
export const heroStagger: Variants = { hidden: {}, visible: { transition: { staggerChildren: 0.2, delayChildren: 0.1 } } };
export const heroItem: Variants = { hidden: { opacity: 0, y: 30 }, visible: { opacity: 1, y: 0, transition: { duration: 0.9, ease: EASE_CURVE } } };